export const GET_FILMS_PENDING = 'GET_FILMS_PENDING';
export const GET_FILMS_REJECTED = 'GET_FILMS_REJECTED';
export const GET_FILMS_FULFILLED = 'GET_FILMS_FULFILLED';
export const FAVOURITE_FILM = 'FAVOURITE_FILM';
export const UNFAVOURITE_FILM = 'UNFAVOURITE_FILM';	